### ISSUE TITLE
Add pre-commit hook to prevent accidentally committing to master

### ISSUE THREAD

**Issue by reed-foster** [qnngroup/qnngds#34]
Something like this:

```yaml
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: no-commit-to-branch
      args: ['--branch', 'main']
    - id: check-added-large-files
    - id: check-merge-conflict
```
